name: genome_analyzer
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - flask=2.0.1
  - flask-caching=2.0.0
  - werkzeug=2.0.1
  - jinja2=3.0.1
  - click=8.0.1
  - itsdangerous=2.0.1
  - biopython=1.81
  - numpy=1.24.3
  - matplotlib=3.7.1
  - seaborn=0.12.2
  - pandas=2.0.3
  - pytest=7.3.1
  - python-dotenv=1.0.0
  - pip
